name: Maintenance CI

on:
  push:
    branches:
      - maintenance/audit-2026-09-03
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: CI=true npm test -- --watchAll=false
      - run: npm run build
